# For local development only.

version: '3'

services:
  phalcon-7.4:
    container_name: proxy-psr11-7.4
    hostname: proxy-psr11-74
    build: docker/7.4
    working_dir: /srv
    volumes:
      - .:/srv

  proxy-psr11-8.0:
    container_name: proxy-psr11-8.0
    hostname: proxy-psr11-80
    build: docker/8.0
    working_dir: /srv
    volumes:
      - .:/srv

